FROM python:3.10.16

WORKDIR /app
COPY . /app

RUN pip install --upgrade pip

RUN pip install rasa

RUN pip install -r requirements.txt

COPY entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/entrypoint.sh

EXPOSE 5005 5055

CMD ["/app/entrypoint.sh"]