version: '3.8'

services:
  mysql:
    image: docker.io/mysql:5.7
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword123
      MYSQL_DATABASE: escola_db
      MYSQL_USER: escola_admin
      MYSQL_PASSWORD: adminpassword456
      MYSQL_LOWER_CASE_TABLE_NAMES: 0
      MYSQL_ALLOW_EMPTY_PASSWORD: "no"
    ports:
      - "3307:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    networks:
      - rede-interna
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: escola-backend
    restart: always
    environment:
      # Variáveis do Banco de Dados
      DB_HOST: mysql
      DB_PORT: 3306
      DB_NAME: escola_db
      DB_USER: root
      DB_PASSWORD: password
      SECRET_KEY: uma_chave_super_secreta_32_caracteres_no_minimo
      
      # Variáveis de Email (SMTP)
      SMTP_SERVER: smtp.gmail.com
      SMTP_PORT: 587
      EMAIL_FROM: elihofnimariano996@gmail.com
      EMAIL_PASSWORD: x j g g i x w a m a v l w r m d
      
      # URL do Frontend para os links de recuperação
      FRONTEND_URL: http://localhost:8080
      
      # Configurações adicionais (opcionais)
      DEBUG: "False"
      ENVIRONMENT: production
      
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    volumes:
      - ./app/uploads:/backend/app/uploads  # Monta a pasta de uploads no container do backend
    networks:
      - rede-interna
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  nginx:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nginx
    restart: always
    ports:
      - "8088:80"
    depends_on:
      - backend
    volumes:
      - ./frontend/public:/usr/share/nginx/html:ro
      -  ./app/uploads:/usr/share/nginx/html/uploads:ro # Monta uploads no diretório correto do Nginx
    networks:
      - rede-interna
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"


networks:
  rede-interna:
    driver: bridge
